### ISSUE TITLE
Add Topics to your Repo

### ISSUE THREAD

**Issue by askpatrickw** [irimitenkan/picam2ctrl#1]
Saw you on the HA forum, just a tip.

More people can find your project if you add [Topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics) to it..

Some suggestions for yours:

- https://github.com/topics/homeassistant
- https://github.com/topics/picamera2
- https://github.com/topics/raspberrypi
- etc

**Comment by irimitenkan** [comment]
Yes, I agree, but  I already set this topics when I started with project at github: on the right side of repro below "About".
