### ISSUE TITLE
Feature Request: Add config options for initial states of the MQTT input values & switches

### ISSUE THREAD

**Issue by Snelso91** [irimitenkan/picam2ctrl#10]
I have noticed that every time I start either picam2ctrl or its service, it always initialises with a set of default values for the MQTT states. For example, "motion enabled" is always true, mjpeg/http stream is always false, timelapse is always false, etc.

What I would like to do is to be able to set all of the starting values of these MQTT states in the picam2ctrl config file.
For example, I would like it so that when the program starts, motion detection is disabled (since I never use it), and MJPEG stream is enabled.

It may be possible to override these in home assistant (HA) with an automation but it would involve re-setting the values every time they are initialised back to the defaults (e.g. motion enabled), to make sure they are the correct (e.g. motion disabled).
Therefore it seemed a lot more logical to me if this was a setting in picam2ctrl, so that the program could be initialised exactly in the default state that the user wants, and HA wouldn't have to fight with the defaults all the time.

Thanks

**Comment by irimitenkan** [comment]
Thank you for your feedback, this is a good idea and usefull. I'll add this feature.

**Comment by irimitenkan** [comment]
@Snelso91 [v0.3.1](https://github.com/irimitenkan/picam2ctrl/releases/tag/v0.3.1) has been released with requested feature, please check

**Comment by Snelso91** [comment]
@irimitenkan thanks, I can confirm the new version works fixes the issue for me :)
