### ISSUE TITLE
Time stamp showing UTC instead of local timezone

### ISSUE THREAD

**Issue by patlhy** [irimitenkan/picam2ctrl#7]
First of all, thanks for publishing this python code. It is a great improvement over the performance of MotioneyeOS which I tried. The delay in the video stream is half of MotioneyeOS.

The timestamp in the video stream is showing UTC instead of local timezone. I changed the following code in picam2.py make it show my local timezone:

timestamp = time.strftime(self._fmt)  => timestamp = dt.now(tz=ZoneInfo("Asia/Singapore")).strftime(self._fmt)

Needed to import the following as well:
from zoneinfo import ZoneInfo

I hope the above is useful for other folks.

**Comment by irimitenkan** [comment]
> First of all, thanks for publishing this python code. It is a great improvement over the performance of MotioneyeOS which I tried. The delay in the video stream is half of MotioneyeOS.

Thank you for feedback.

> The timestamp in the video stream is showing UTC instead of local timezone. I changed the following code in picam2.py make it show my local timezone:

Ok. What do you get if you open python console and entering:

```
import time
print (time.tzname)

```
I don't get UTC , but I'm not sure if strftime depends on configured system timezone. 
On the other hand there is the '%z' format parameter:

`Time zone offset indicating a positive or negative time difference from UTC/GMT of the form +HHMM or -HHMM, where H represents decimal hour digits and M represents decimal minute digits [-23:59, +23:59]. `

**Comment by patlhy** [comment]
Thanks for your response. I didn't setup my system time in my fresh Raspberry Pi OS SD card to my own timezone. That explain why I had to add additional lines of code for the time stamp to show the correct time zone.

>>> import time
>>> print (time.tzname)
('GMT', 'BST')
