### ISSUE TITLE
Questions: Pi Camera Module 3 On Pi Zero 2 W & Video Capture

### ISSUE THREAD

**Issue by JS1Dev** [irimitenkan/picam2ctrl#8]
- Will this work with the Pi Camera Module 3 on a Pi Zero 2 W?
-- I ask because I'm not sure if [Raspberry Pi Camera - Home Assistant](https://www.home-assistant.io/integrations/rpi_camera/) will work for me per [this](https://community.home-assistant.io/t/rpi-camera-for-home-assistant-os/340841/4?u=isthisright), and this may be a better option anyway.
- For copying of the latest files (image/video) the Readme says "resp. SCP support to be used to copy latest snapshot picture / mp4 video to a SSH server", I'm just dabbling in Linux and I see [SCP](https://www.computerhope.com/unix/scp.htm), is there any UI in Home Assistant that does this behind the scenes or is that just something I have to do manually once I set it up?
- Would the Camera Module 3 be configured as quality HIGH or VERY_HIGH?
- I see in the Readme "'audio':true - enable/disable audio for mp4 file resp UDP streaming (http actually not supported)." but the HTTPServer / MJPEG Stream section's example uses "http" does that mean that if I want sound too, I have to use https?

**Comment by irimitenkan** [comment]
> * Will this work with the Pi Camera Module 3 on a Pi Zero 2 W?

Yes, but you'll need a special [cable](https://www.raspberrypi.com/products/camera-cable/)

>     * For copying of the latest files (image/video) the Readme says "resp. SCP support to be used to copy latest snapshot picture / mp4 video to a SSH server", I'm just dabbling in Linux and I see [SCP](https://www.computerhope.com/unix/scp.htm), is there any UI in Home Assistant that does this behind the scenes or is that just something I have to do manually once I set it up?


Setup of SSH server/client depends on the linux distribution's packet manager. You'll find  HOWTOs for each distro.


>     * I see in the Readme "'audio':true - enable/disable audio for mp4 file resp UDP streaming (http actually not supported)." but the HTTPServer / MJPEG Stream section's example uses "http" does that mean that if I want sound too, I have to use https?

Actually https is not supported.  I recommend a VPN connection to your home server.

**Comment by JS1Dev** [comment]
Hi @irimitenkan, thanks so much for your reply, I really appreciate it!

Yes, I already have a cable that I ordered from [here](https://www.electromaker.io/shop/product/camera-cable-for-raspberry-pi-zero) on it's way :).  My main question though was more general, though indirectly I _think_ you've answered it. It seems that your integration will work for me despite my Windows VM ([Hypervisor specific configuration](https://www.home-assistant.io/installation/windows#hypervisor-specific-configuration)) installation, correct?
- My concern is/was related to how I can' use the [Raspberry Pi Camera - Home Assistant ](https://www.home-assistant.io/integrations/rpi_camera/) integration as it calls out in it's documentation that it won't work for me as I don't have a Core installation (“This integration is only available on Home Assistant Core installation types").

Thanks for the tip regarding the dependency of the dist's packet manager and the reference to the HOWTOs for each, I'll look into better understanding that 

Gotcha' on the https not being supported - I actually have been using http with a VPN connection to my home server because I like that security, though I was looking to go down the https route but maybe I won't now

**Comment by irimitenkan** [comment]
Hi [JS1Dev](https://github.com/JS1Dev)

ok, I don't have experience with HA OS (only played with a VM installation), but yes I assume integration of picam2ctrl (running on a PI zero) is possible if you install the openssh and mosquitto addon. To be more flexible and not to get trouble with HA OS restrictions I'm using RPI OS + HA docker installation. It is running quite stable here even on my old RPI V2 server.

**Comment by JS1Dev** [comment]
Thanks @irimitenkan, I guess the only way to know for sure is to give it a shot :).  I'm waiting for the pi 0 2 W/ camera / cable I ordered to show up, so I thought I'd try to do some research while I'm waiting to hit the ground running as best I can.  Fingers crossed!

Regarding my HA installation, I'm planning on doing some local voice stuff that'll be a bit resource hungry and am trying to keep everything on 1 machine (at least for now).  I've had the installation in place for a few years now and haven't noticed any restrictions but maybe I just luckily haven't run into any yet with what I've done so far.

**Comment by irimitenkan** [comment]
closed
