### ISSUE TITLE
Connection to MQTT without TLS not working

### ISSUE THREAD

**Issue by jens-stutte** [irimitenkan/picam2ctrl#9]
It seems that `paho.mqtt.client` uses TLS if any tls parameter has been set via `tls_set`. Changing the connection to:

```
            try:
                self.username_pw_set(
                    self.cfg.MQTTBroker.username,
                    self.cfg.MQTTBroker.password)

                # Use TLS at all?
                # As soon as tls_set is called, paho.mqtt.client assumes
                # we have an encrypred connection., it seems.
                if not self.cfg.MQTTBroker.insecure:
                    # no client certificate needed
                    if len(self.cfg.MQTTBroker.clientcertfile) and \
                       len(self.cfg.MQTTBroker.clientkeyfile):
                        self.tls_set(certfile=self.cfg.MQTTBroker.clientcertfile,
                                     keyfile=self.cfg.MQTTBroker.clientkeyfile,
                                     cert_reqs=ssl.CERT_REQUIRED)
                    else:
                        # some users reported connection problems due to this call
                        # but in my environmet this is a MUST
                        self.tls_set(cert_reqs=ssl.CERT_NONE)

                self.connect(
                    self.cfg.MQTTBroker.host,
                    self.cfg.MQTTBroker.port)
```

works for me with HA's internal MQTT broker on the non-secured port. (Yes, this is insecure, of course, and you should really trust your network to do this).

However, this change would break connections for existing TLS configurations that have `insecure` set to `true`, which seems to be the default configuration (and has no consequences at all currently). To avoid this, one could add a new flag for this option.

**Comment by irimitenkan** [comment]
The problem was I didn't see that port 1883 has to be used for non-ssl and port 8883 has to be used for ssl connections.
I double checked bugfix with mosquitto docker installation and with most recent HASS OS + mosquitto add-on.
